"""Level 9 revised tests: assembly cleanup + single featured image."""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

def test_assembler_source_cleaned():
    src = (Path(__file__).parent.parent / "core" / "graph.py").read_text(encoding="utf-8")
    assert "Table of Contents" not in src
    assert "📊 Section" not in src
    assert "Key Takeaways" not in src
    assert "Generated by ContentForge AI" not in src
    print("[OK] assembler cleanup verified")

def test_engagement_css_preserves_centering():
    """Guard: the margin shorthand with !important would kill WP auto-centering."""
    import re
    from core.exporters.engagement import ENGAGEMENT_BLOCK
    assert not re.search(r"margin:\s*[^;]+!important", ENGAGEMENT_BLOCK), \
        "margin shorthand with !important breaks WordPress centered layout"
    assert "margin-top" in ENGAGEMENT_BLOCK
    assert "overflow-x:auto" in ENGAGEMENT_BLOCK  # mobile table scrolling
    print("[OK] engagement CSS preserves centering verified")

def test_pil_fallback_image(tmp_path, monkeypatch):
    import core.exporters.image_generator as ig
    monkeypatch.setattr(ig, "UNISCOLIAN_UPLOADS_DIR", tmp_path)
    import httpx
    def fake_get(*a, **k): raise httpx.ConnectError("offline")
    monkeypatch.setattr(ig.httpx, "get", fake_get)
    monkeypatch.setattr(ig, "_hf_space_api", lambda *a, **k: None)
    monkeypatch.setattr(ig, "_hf_flux_inference", lambda *a, **k: None)
    res = ig.generate_featured_image("test topic", "Best Test Topic Guide 2026", "test-topic")
    assert res["file_exists"] is True
    assert res["source"] == "pil"
    img_path = tmp_path / res["relative_path"].replace("wp-content/uploads/", "")
    assert img_path.exists()
    from PIL import Image
    with Image.open(img_path) as im:
        assert im.size == (900, 752)
    print("[OK] PIL fallback image 900x752 verified")

def main():
    test_assembler_source_cleaned()
    test_engagement_css_preserves_centering()
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        class M:  # tiny monkeypatch stand-in
            def setattr(self, obj, name, val): setattr(obj, name, val)
        test_pil_fallback_image(Path(d), M())
    print("LEVEL 9 REVISED VERIFIED — cleanup + single image OK.")

if __name__ == "__main__":
    main()
