"""Generate a clean, print-styled PDF from an assembled blog."""
from __future__ import annotations
from datetime import datetime
from pathlib import Path

from app.config import logger
from core.exporters.markdown_converter import markdown_to_html

PDF_CSS = """
@page { size: A4; margin: 2cm; }
body { font-family: Helvetica, Arial, sans-serif; font-size: 10.5pt; line-height: 1.6; color: #222222; }
h1 { font-size: 19pt; color: #1a365d; margin: 0 0 6pt 0; }
h2 { font-size: 14pt; color: #1f3a5f; margin: 14pt 0 6pt 0; }
h3 { font-size: 12pt; color: #234; margin: 10pt 0 4pt 0; }
h4 { font-size: 11pt; }
p { margin: 0 0 8pt 0; }
table { width: 100%; border-collapse: collapse; margin: 10pt 0; }
th, td { border: 1px solid #999999; padding: 5pt 6pt; font-size: 9.5pt; text-align: left; }
th { background-color: #e8eef7; }
blockquote { border-left: 3px solid #2563eb; background: #f2f7ff; padding: 8pt 10pt; margin: 10pt 0; }
ul, ol { margin: 0 0 8pt 0; padding-left: 18pt; }
li { margin-bottom: 3pt; }
hr { border: none; border-top: 1px solid #cccccc; margin: 12pt 0; }
.meta { color: #777777; font-size: 8.5pt; margin-bottom: 14pt; }
a { color: #2563eb; text-decoration: none; }
"""


def blog_to_pdf(markdown_text: str, title: str, output_path: Path) -> Path:
    """Convert blog markdown to PDF. Returns the output path."""
    body = markdown_to_html(markdown_text, include_images=False)
    html = f"""<html><head><meta charset="utf-8"><style>{PDF_CSS}</style></head><body>
<div class="meta">Generated by ContentForge AI &bull; {datetime.now().strftime('%B %d, %Y')}</div>
{body}
</body></html>"""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    from xhtml2pdf import pisa
    with open(output_path, "wb") as f:
        status = pisa.CreatePDF(src=html, dest=f)
    if status.err:
        raise RuntimeError(f"PDF generation failed with errors: {status.err}")

    logger.info("PDF exported: %s (%d KB)", output_path, output_path.stat().st_size // 1024)
    return output_path
